name: Package
on: [push, pull_request]

jobs:
  package-macos:
    runs-on: macos-latest
    env:
      PIPENV_VENV_IN_PROJECT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
        run: |
          pip3 install pipenv
          pipenv install PyQt6 lxml
          pipenv run pip install PyQt6 lxml
      - name: Package visionui
        run: |
          rm -rf build dist
          pipenv run python setup.py py2app
          open dist/visionui.app
      - name: Archive macOS app
        run: |
          cd dist/
          tar czf visionui.tgz visionui.app
      - uses: actions/upload-artifact@v3
        with:
          name: macOS artifact
          path: dist/visionui.tgz
  package-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller PyQt6 lxml
      - name: Package visionui
        run: |
          pyinstaller --hidden-import=PyQt6 --hidden-import=lxml -F -n "visionui" -c visionui.py -p ./librarys -p ./
      - uses: actions/upload-artifact@v3
        with:
          name: Windows artifact
          path: dist/visionui.exe
  package-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python Environment
        run: |
          pip3 install pyinstaller PyQt6 lxml
      - name: Package visionui
        run: |
          pyinstaller --hidden-import=PyQt6 --hidden-import=lxml -F -n "visionui" -c visionui.py -p ./librarys -p ./
      - uses: actions/upload-artifact@v3
        with:
          name: Linux artifact
          path: dist/visionui
